const data = [
  {
    id: 'project-2',
    title: `Space Traveler's Hub`,
    image: 'images/space-traveler.png',
    github: 'https://github.com/ridwanediallo/Space-travelers--hub',
    liveLink: 'https://ridwanediallo.github.io/Space-travelers--hub/',
    tech1: 'React',
    tech2: 'Redux',
    tech3: 'Bootstrap',
    tech4: ' React-Router',
    end: 'Front-End Dev',
    description: `Space Travelers' hub is an app built React, React-Router, Redux Toolkit, and Bootstrap. It allows the user to reserve a rocket and joined a mission. The app fetches the data from an external API.`,
  },
  {
    id: 'project-3',
    title: 'Tonic',
    canopy: 'Canopy',
    image: 'images/countries.png',
    github: 'https://github.com/ridwanediallo/The-Countries',
    liveLink: 'https://rid-the-counties.netlify.app/',
    tech1: 'React',
    tech2: 'Redux',
    tech3: 'React-Router',
    // tech4: ' React-Router',
    description:
      'The Countries is an app built React, React-Router, Redux Toolkit, and Bootstrap. It makes use of the RESTful Countries API to display information about countries such as their flag, population, timezone, and so on. It has two versions with different layouts.',
  },
  {
    id: 'project-4',
    title: 'BookStore CMS',
    canopy: 'Canopy',
    image: 'images/bookstore.png',
    github: 'https://github.com/ridwanediallo/Bookstore-CMS',
    liveLink: 'https://rid-bookstore-cms.netlify.app/',
    tech1: 'React',
    // tech4: ' React-Router',
    tech2: 'Redux',
    tech3: 'React-Router',
    end: 'Front-End Dev',
    description: `This is an app for users to add a book's title, its author and category. Once added the book's data are saved to an external API and when the app reloads, it fetches the data from the server and displays them on the screen.`,
  },
];

export default data;
